### ISSUE TITLE
Set image range default

### ISSUE THREAD

**Issue by djraymondnm** [dankelley/gri#8]
I am attaching a gri file and a link to a NetCDF file that supplies the data for it.  The gri file makes two shaded fill plots from gridded data. The command "set image range" is not invoked in either case.  In the first case the the image range is picked up automatically.  In the second case gri tries to use the previously set image range, which is inappropriate for the second grid.

I see a couple of possible fixes that shouldn't break existing applications.

1. Make gri check for a new image range whenever a new grid is read in without the need to call ``set image range``.

2. Make ``set image range``  determine an image range from the data if it is given no arguments.

Here is the link to the netcdf file:
[http://kestrel.nmt.edu/~raymond/data/gri_test_case.nc](http://kestrel.nmt.edu/~raymond/data/gri_test_case.nc)

Here is the gri file:

```
open gri_test_case.nc netcdf
set missing value 1.0e30
set x size 10
set y size 10
set x margin 6
set y margin 6
set x axis unknown
set y axis unknown
set x name "lon"
set y name "lat"
set clip on
read grid x = "lon"
read grid y = "lat"
read grid data = "rh"
convert grid to image size 200 200
draw image
draw axes if needed
draw image palette
set x size 10
set y size 10
set x margin 18
set y margin 6
set x axis unknown
set y axis unknown
set x name "lon"
set y name "lat"
set clip on
read grid x = "lon"
read grid y = "lat"
read grid data = "mflux"
convert grid to image size 200 200
draw image
draw axes if needed
```

**Comment by djraymondnm** [comment]
Oops!  The file name in the gri script should be "gri_test_case.nc" rather than "test_case.nc".  Sorry, I changed the name when moving it to my data repository without considering the consequences of this.  Alternatively, simply rename the netcdf file to "test_case.nc".

**Comment by dankelley** [comment]
Thanks. I modified the ``develop`` branch to have a new command
```
set image range automatic
```
and I wonder if that helps with your issue?

**Comment by djraymondnm** [comment]
That should do it.  I assume that a subsequent call to set image range with
specific values will override this?

I'll give it a try.

Dave

**Comment by dankelley** [comment]
Before this becomes official, it will need more work. I wonder if you can help with the following? (You'll need to do ``git pull`` again to update.)

1. Check the docs to see if they are clear and sufficient. To see them, either look in the "info" , or do ``help set image range`` in an interactive session. (I think it's best to use "info", if you are familiar with how it works.)

2. Try a test case in which the other style of ``set image range`` is used. Ideally, try both (a) a case in which the same scale is used for a series of images and (b) a different style is used for each image.

I know I could do both of these things myself but it's best for a user to do them, in general. That way, I can be reasonably sure that the changes will stand the test of time.  Thanks!!

PS. when (or if) you think things are ok, please post here, and then close the issue. My policy is that only those who post issues should close them. That's a way to ensure they are OK with the changes.

**Comment by dankelley** [comment]
Somehow I must have deleted a comment by @djraymondnm so I'm putting it below (formatted a bit).

I spoke too soon. Here is a gri file using the previous data set:

```
open gri_test_case.nc netcdf
set missing value 1.0e30
set x size 10
set y size 10
set x margin 6
set y margin 6
set x axis unknown
set y axis unknown
set x name "lon"
set y name "lat"
set clip on
read grid x = "lon"
read grid y = "lat"
read grid data = "rh"
#set image range automatic
#set image range 0.86 0.94
set image colorscale hsb 0.666 1 1 0.86 hsb 0 1 1 0.94 increment 0.01
convert grid to image
draw image
draw axes if needed
draw image palette axisbottom box 6 18 16 18.7
set x size 10
set y size 10
set x margin 20
set y margin 6
set x axis unknown
set y axis unknown
set x name "lon"
set y name "lat"
set clip on
read grid x = "lon"
read grid y = "lat"
read grid data = "mflux"
#set image range automatic
convert grid to image size 200 200
draw image
draw axes if needed
draw image palette axisbottom box 20 18 30 18.7
```

**CASE 1**

If the ``set image range automatic`` and explicit range setting commands are commented out as shown, the ranges are determined automatically for both subplots with no problem, with the following message from gri:

```
$ gri test_case.gri
Warning: Gri version number (2.12.24) doesn't match version (2.12.23) in library file gri.cmd
convert grid to image':
Image is 128 wide and 128 tall, with x in range (143,150) and y in range (11, 18)
convert grid to image':
Image is 200 wide and 200 tall, with x in range (143,150) and y in range (11, 18)
```

The warning seems to be cosmetic, having to do with the version number in the gri.cmd file. This works for multiple subplots with different image ranges, implying that the range is redetermined with each new subplot. This is an improvement over previous behavior. However, if the range is set explicitly in the first plot (by uncommenting the explicit range declaration), it is not redetermined automatically in the second plot, which then uses the range settings from the first plot.

**CASE 2**

With ``set image range automatic`` active, gri dies with the following:

```
$ gri test_case.gri
Warning: Gri version number (2.12.24) doesn't match version (2.12.23) in library file gri.cmd
PROPER USAGE: set image range automatic'
ERROR: Wrong number of words in command
Bad command:set image range automatic'
Error at test_case.gri:15
```
Something is still wrong here.

**Comment by djraymondnm** [comment]
The `set image range automatic` now does what it should.  It doesn't work well with `set image colorscale`, as the color increment appears to take on a very coarse value.  This doesn't bother me, but it might be nice to have the automatic option set a sensible color increment.

In a possibly related issue, `set image grayscale` doesn't seem to work at all now.  The script
```
open test_case.nc netcdf
set missing value 1.0e30
set x size 10
set y size 10
set x margin 6
set y margin 6
set x axis unknown
set y axis unknown
set x name "lon"
set y name "lat"
set clip on
read grid x = "lon"
read grid y = "lat"
read grid data = "rh"
set image range 0.86 0.94
set image grayscale 0.86 0.94
convert grid to image
draw image
draw axes if needed
```
results in
```
loro:/data/raymond$ gri test_case.gri
PROPER USAGE: `set image grayscale [black .bl. white .wh. [increment .inc.]]'
ERROR: Can't understand command.
 Bad command:  `set image grayscale 0.86 0.94'
 Error at test_case.gri:16
```

**Comment by dankelley** [comment]
The line
```
set image grayscale 0.86 0.94
```
does not match the syntax. Check the "USAGE" line ... it says that this is to be written e.g.
```
set image grayscale black 0.86 white 0.94
```

**Comment by dankelley** [comment]
I am starting to worry about how I've coded this ``set image range automatic``. It is interacting with other things, as we are discovering, and I'm worried it is going to break code. Besides, we are not really making it "automatic"; all we are doing is to make it automatic in the case of conversion of grid to image, and that's not the only way to have images.

However, a command
```
set image range from grid
```
would seem to make sense. This would have the advantage of clarity for the reader and for the developer!  It would also not cause the creation of any new global variables (which is the problem with the "solution" that I had been trying here, as you know from your previous examination of the code).

So, what do you think? Can I start over and simply add this "from grid" command? I feel that would be simple to code, and it would allay my worry about breaking other people's gri scripts.  (Some people are using scripts that are many years old, and any behaviour change worries me because it could bite them, the next time they generate a yearly data report or something.)

**Comment by dankelley** [comment]
I gave up on this idea of ``set image range automatic``. The problem was that the new scheme was having too many side effects on existing code, because it had invented a new global variable that had to be set or checked in lots of different places.

My new idea is ``set image range from grid``. This has been coded into the ``develop`` branch. A test code for it is given in the [test suite](https://github.com/dankelley/gri-issues/tree/master/8).

To try out the new style, download the ``develop`` branch, build, and then run the [test suite](https://github.com/dankelley/gri-issues/tree/master/8) code, ``8a.gri``.

**Comment by djraymondnm** [comment]
`set image range from grid` seems to work well in all the tests that I have been able to think of.
